Allow opening deeplinks with custom schema
SecUSo/privacy-friendly-qr-scanner pull request #225
Opened 2024-03-10 22:34 UTC by jokakilla

Before this change opening URLs with a schema different from http/https wasn't possible because the code always prepended http.
With this change http is only prepended when no schema is present.

2024-03-10 22:36 UTC, jokakilla commented
https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/224

2024-04-22 10:51 UTC, coderPaddyS requested changes

2024-04-22 10:51 UTC, coderPaddyS commented on app/src/main/java/com/secuso/privacyfriendlycodescanner/qrscanner/ui/resultfragments/URLResultFragment.java
> +            if (!qrurl.toLowerCase().contains("://")) {
This does not respect the RFC 3986 which specifies what a valid protocol-scheme looks like.
A regex to match that should be `^[a-zA-Z][a-zA-Z0-9+.-]*:.*$`, but this needs to be checked and tested.

2024-04-23 14:07 UTC, coderPaddyS commented on app/src/main/java/com/secuso/privacyfriendlycodescanner/qrscanner/ui/resultfragments/URLResultFragment.java
> +            if (!qrurl.toLowerCase().contains("://")) {
Thanks for improving on this! :smile: 
I'll take a look and test your changes myself in the next few days and will check if using https as default won't break any expected use case.
We'd appreciate if you'd rebase your changes onto `development` and target `development` for the PR.

2024-06-09 20:03 UTC, jokakilla commented
Any chance this change will be merged? Should I do any further adaptions?

2024-07-08 06:05 UTC, coderPaddyS approved these changes

2024-07-08 06:06 UTC, coderPaddyS commented
I'm sorry for taking this long.
If looked into branch and noticed that a rebase is not necessary as no merge conflicts happen.
Thank you for your contribution :D

2024-07-08 06:07 UTC, merged